data:
    dataset: "biked"
    image_size: 256
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 4

model:
    type: "simple"
    in_channels: 1
    out_ch: 1
    ch: 64
    ch_mult: [1, 2, 2, 2, 2, 2]
    num_res_blocks: 1
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 16
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 1000
    validation_freq: 1000

sampling:
    batch_size: 20
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00005
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
